version: "3"

services:
  traefik:
    image: library/traefik:v2.6
    container_name: 'global_traefik'
    restart: "always"
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
      - "1433:1433"
      - "5432:5432"
    volumes:
      - ./.docker/traefik:/etc/traefik
      - ~/ssl:/etc/traefik/ssl
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - default

networks:
  default:
    external:
      name: "gateway"
